### ISSUE TITLE
Kiali render hostnames as individual service instead of serviceentry as whole

### ISSUE THREAD

**Issue by im-Amitto** [kiali/kiali#6962]
### Describe the bug
Loom Video :-> https://www.loom.com/share/2c1906c2ffe042dcbf6d96ca9e4f7ef4
A serviceentry is supposed to be visualised as single icon in graph does not matter how many number of hostnames it has in it.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: api.headout.com
spec:
  hosts:
  - api.example.com
  - api.example2.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
```

It should be shown as a single icon but kiali is showing 1 service icon per hostname. It does not happen always. It does show the service entry as a single icon sometime but goes back to showing one icon per hostname on refresh.

### Expected Behavior
Single icon for a single service entry

### What are the steps to reproduce this bug?

1. Create a serviceentry with two hostname
2. Visualise the traffic

### Environment

- **Kiali version:** v1.76.1 (0f96891475ab41b10821ae8e1850572fbcd1505f)
- **Istio version:** 1.18.2
- **Kubernetes version:**  v1.28.4-eks-8cb36c9
- **Prometheus** 2.48.0

**Comment by hhovsepy** [comment]
I confirm seeing SE per host in the graph, this is because Istio is generating a Service per SE host in Service Registry.

**Comment by im-Amitto** [comment]
@hhovsepy but it does not happen everytime, sometime i get the visualisation that i want where it's shown as a single entity.
Here `mb-domain` contain more than 400 hostname.
<img width="428" alt="Screenshot 2023-12-18 at 9 40 49 AM" src="https://github.com/kiali/kiali/assets/29653282/66ae4b8e-559c-4bec-b13d-23ca517f1f62">

**Comment by hhovsepy** [comment]
Seems like Kiali would need a new functionality in a Graph. A checkbox to merge all URLs of the ServiceEntry into one or show it separately.

**Comment by jshaughn** [comment]
> Seems like Kiali would need a new functionality in a Graph. A checkbox to merge all URLs of the ServiceEntry into one or show it separately.

@hhovsepy After thinking about this I think this should not be an option, I think the requested behavior is the intended behavior, and only a single ServiceEntry node should exist for all of the hosts.  And so, this does seem like a bug, and actually a regression, as I believe the code intends to consolidate into a single node.

Note that this is still namespace specific, so if a ServiceEntry is exported to multiple namespaces, a separate ServiceEntry node could show up in each of the namespaces, because Kiali treats each export as a separate SE.

**Comment by im-Amitto** [comment]
> > Seems like Kiali would need a new functionality in a Graph. A checkbox to merge all URLs of the ServiceEntry into one or show it separately.
> 
> @hhovsepy After thinking about this I think this should not be an option, I think the requested behavior is the intended behavior, and only a single ServiceEntry node should exist for all of the hosts. And so, this does seem like a bug, and actually a regression, as I believe the code intends to consolidate into a single node.
> 
Yes, that's what i wanted to point out
> Note that this is still namespace specific, so if a ServiceEntry is exported to multiple namespaces, a separate ServiceEntry node could show up in each of the namespaces, because Kiali treats each export as a separate SE.
Yes, currently it shows graph in two ways. They are seen randomly on page refresh.
1. SE in namespace level, one icon for each SE (The one the feels nice)
2. Each host as a seprate service, in this the service are not shown at namespace level.

I would actually love if we can have a 3rd way where we see 1 symbol per SE but globally instead of showing at namespace level.

Anyway, even the expected behaviour[1], works completely fine.


If someone can help me find the piece od code that renders the graph i might be able to figure out the fix.

**Comment by jshaughn** [comment]
> I would actually love if we can have a 3rd way where we see 1 symbol per SE but globally instead of showing at namespace level.

This has been requested before, but sort of breaks the model, so unlikely to do this option.

**Comment by jshaughn** [comment]
@im-Amitto Just to confirm, when you see the bad behavior, the many nodes are actually service nodes (triangles), not service entry nodes (5 sides), right?

**Comment by im-Amitto** [comment]
> @im-Amitto Just to confirm, when you see the bad behavior, the many nodes are actually service nodes (triangles), not service entry nodes (5 sides), right?

yes, exactly

**Comment by lonnixrdc** [comment]
I have had the same behavior even when my SE only has 1 host in it. Sometimes I see the SE icon, other times I just see a triangle and the host listed out. I think there are 2 issues in play, both related to how Kiali displays ServiceEntries

1. Multiple hosts showing up (or not showing up) for the same SE
2. The SE sometimes not showing up and other times showing up

**Comment by jshaughn** [comment]
I'm seeing the behavior, very strange...

**Comment by jshaughn** [comment]
A fix has been merged and it will be included in Kiali 1.79, due for release Jan 22.  If you need a backport to an existing version, please let me know.

**Comment by im-Amitto** [comment]
> A fix has been merged and it will be included in Kiali 1.79, due for release Jan 22. If you need a backport to an existing version, please let me know.

No urgency, but would love to understand how to backport stuff to an existing version.

**Comment by jshaughn** [comment]
> No urgency, but would love to understand how to backport stuff to an existing version.

Backporting typically consists of using a git cherry-pick of a merged PR from the current version to an older version.  If it doesn't map perfectly then manual edits are needed to make sure the change is compatible.  Once backported we have defined some git actions to release a new patch version upstream.

**Comment by im-Amitto** [comment]
@jshaughn Issue still seems to be persisting

Kiali : v1.79.0 (d5068956c3d1144a16306b397f5ccce614c1d810)
Kiali Container : v1.79.0

Service Mesh
Istio : 1.18.2
Prometheus : 2.48.0
Kubernetes : v1.28.4-eks-8cb36c9


Do i need to re-create the service entries?

**Comment by jshaughn** [comment]
@im-Amitto , no, I don't think recreating the service entries would matter.  @lonnixrdc , have you been able to try out v1.79?

**Comment by jshaughn** [comment]
@im-Amitto Can you try it with and without the "Show Service Nodes" Graph Display option enabled?  If you are still having a problem we may need to start the debugging process again, as I'm wondering if it's the same issue.  Prior to the fix it was easily reproducible, but after the fix were were unable to reproduce on our side.

**Comment by jshaughn** [comment]
@im-Amitto @lonnixrdc , anything else to report here, I'm not sure what could still be the issue.

**Comment by jshaughn** [comment]
@im-Amitto Thanks for the feedback, I will look into this again.  Just to be clear, the previous behavior would "flip-flop" between the single node and the multiple nodes.  Is that still true, or now do you always see expanded number of nodes?

**Comment by jshaughn** [comment]
@im-Amitto Just to confirm, the ServiceEntry in your screenshot is still defined as in the original description?   I see above that the`mb-domains` ServiceEntry is defined in the `istio-system` namespace.  By default it would be exported to all namespaces, but if you have defined an `export_to`, something like:
```
  exportTo:
  - "."
 ```
Then there could be an issue.  I just need to make sure that the `headout-mystique` namespace can access the `mb-domains` ServiceEntry definition.

One other test you could maybe try, just for sanity, would be to define the`mb-domains` serviceEntry directly in the `headout-mystique` namespace, and therefore not rely on `exportTo`.  If that worked it would indicate that Kiali has a bug in its handling of `exportTo`.  Actually, this would be a great test, because I do see an assumption in the code that makes me wonder if we are handling `exportTo` correctly.

**Comment by im-Amitto** [comment]
> export_to

@jshaughn 
Aware about this, we are not using it in any service entry.

> would be to define the `mb-domains` serviceEntry directly in the headout-mystique namespace

What worked
- Creating SE in `headout-mystique`

What did not
- Creating SE with exportTo set to `*` or even with `-headout-mystique`

I can't really use it as the SE are pretty common among different micro-service around the namespaces.

**Comment by jshaughn** [comment]
@im-Amitto OK, thanks for the quick feedback.  It seems Kiali has an issue dealing with `exportTo`, it's not picking up the fact that, by default, your definition should be available to all namespaces.  I'll look into it more today...

**Comment by jshaughn** [comment]
@im-Amitto I have opened https://github.com/kiali/kiali/issues/7153 for this new problem.
